export default [
    {
        title:"ផ្ទាំងព័ត៌មាន",
        to:"/",
        children:[],
        icon:"mdi-monitor-dashboard"
    },
    // {
    //     title:"ការគ្រប់គ្រងបុគ្គលិក",
    //     icon:"mdi-card-account-details-outline",
    //     children:[
    //         {
    //             title:"តារាងបុគ្គលិក",
    //             to:"/employee/list",
    //             children:[],
    //             icon:"mdi-text-account"
    //         },
    //         {
    //             title:"បញ្ចូលថ្មីបុគ្គលិក",
    //             to:'/employee/create',
    //             children:[],
    //             icon:"mdi-account-plus-outline"
    //         },
    //         {
    //             title:"ប្រតិបត្តិការបុគ្គលិក",
    //             to:"/employee/transaction/list",
    //             children:[],
    //             icon:"mdi-text-account"
    //         },
    //         {
    //             title:"របាយការណ៍បុគ្គលិក",
    //             to:"/employee/report",
    //             children:[],
    //             icon:"mdi-chart-bar"
    //         },
    //         {
    //             title:"របាយការណ៍ប្រតិបត្តិការបុគ្គលិក",
    //             to:"/employee/transaction/report",
    //             children:[],
    //             icon:"mdi-chart-areaspline-variant"
    //         }
    //     ]
    // },
    // {
    //     title:"ការគ្រប់គ្រងអវត្តមាន",
    //     icon:"mdi-alert-octagon-outline",
    //     children:[
    //         {
    //             title:"តារាងអវត្តមាន",
    //             to:"/attendance/list",
    //             children:[],
    //             icon:"mdi-table-alert"
    //         },
    //         {
    //             title:"បញ្ជូលអវត្តមាន",
    //             to:"/attendance/create",
    //             children:[],
    //             icon:"mdi-pen-plus"
    //         },
    //         {
    //             title:"របាយការណ៍អវត្តមាន",
    //             to:"/attendance/report",
    //             children:[],
    //             icon:"mdi-chart-bar-stacked"
    //         },
    //     ]
    // },
    // {
    //     title:"ការកំណត់",
    //     icon:"mdi-cog-outline",
    //     children:[
    //         {
    //             title:"ឈ្នោះនៃប្រព័ន្ធ",
    //             to:"/setting/label",
    //             children:[],
    //             icon:"mdi-format-title"
    //         },
    //         {
    //             title:"អ្នកប្រើប្រាស់",
    //             icon:"mdi-account-star",
    //             children:[
    //                 {
    //                     title:"តារាងអ្នកប្រើប្រាស់",
    //                     to:"/setting/user/list",
    //                     children:[],
    //                     icon:"mdi-table-account"
    //                 },
    //                 {
    //                     title:"គណនី",
    //                     to:"/setting/user/profile",
    //                     children:[],
    //                     icon:"mdi-account-circle-outline"
    //                 }
    //             ]
    //         },
    //         {
    //             title:"មុខដំណែង",
    //             to:"/setting/position/list",
    //             children:[],
    //             icon:"mdi-folder-key-network-outline"
    //         },
    //         {
    //             title:"ការិយាល័យ/ផ្នែក",
    //             to:"/setting/office/list",
    //             children:[],
    //             icon:"mdi-folder-key-network-outline"
    //         },
    //     ]
    // },
]